class AWSInstanceType:
    def __init__(self, instancetype):
        self.instanceType = self.getInstanceDesc(instancetype)

    def getInstanceDesc(self, instance):
        instanceMap = \
            {
                "c3.2xlarge": {
                    "vCPU": 8,
                    "Memory (GiB)": "15",
                    "Storage (GB)": "2 x 80 SSD",
                    "Networking Performance": "High",
                    "Physical Processor": "Intel Xeon E5-2680 v2",
                    "Clock Speed (GHz)": "2.8",
                    "Intel AVX†": "Yes",
                    "Intel AVX2†": "-",
                    "Intel Turbo": "Yes",
                    "EBS OPT": "Yes",
                    "Enhanced Networking†": "Yes"
                },
                "c3.4xlarge": {
                    "vCPU": 16,
                    "Memory (GiB)": "30",
                    "Storage (GB)": "2 x 160 SSD",
                    "Networking Performance": "High",
                    "Physical Processor": "Intel Xeon E5-2680 v2",
                    "Clock Speed (GHz)": "2.8",
                    "Intel AVX†": "Yes",
                    "Intel AVX2†": "-",
                    "Intel Turbo": "Yes",
                    "EBS OPT": "Yes",
                    "Enhanced Networking†": "Yes"
                },
                "c3.8xlarge": {
                    "vCPU": 32,
                    "Memory (GiB)": "60",
                    "Storage (GB)": "2 x 320 SSD",
                    "Networking Performance": "10 Gigabit",
                    "Physical Processor": "Intel Xeon E5-2680 v2",
                    "Clock Speed (GHz)": "2.8",
                    "Intel AVX†": "Yes",
                    "Intel AVX2†": "-",
                    "Intel Turbo": "Yes",
                    "EBS OPT": "-",
                    "Enhanced Networking†": "Yes"
                },
                "c3.large": {
                    "vCPU": 2,
                    "Memory (GiB)": "3.75",
                    "Storage (GB)": "2 x 16 SSD",
                    "Networking Performance": "Moderate",
                    "Physical Processor": "Intel Xeon E5-2680 v2",
                    "Clock Speed (GHz)": "2.8",
                    "Intel AVX†": "Yes",
                    "Intel AVX2†": "-",
                    "Intel Turbo": "Yes",
                    "EBS OPT": "-",
                    "Enhanced Networking†": "Yes"
                },
                "c3.xlarge": {
                    "vCPU": 4,
                    "Memory (GiB)": "7.5",
                    "Storage (GB)": "2 x 40 SSD",
                    "Networking Performance": "Moderate",
                    "Physical Processor": "Intel Xeon E5-2680 v2",
                    "Clock Speed (GHz)": "2.8",
                    "Intel AVX†": "Yes",
                    "Intel AVX2†": "-",
                    "Intel Turbo": "Yes",
                    "EBS OPT": "Yes",
                    "Enhanced Networking†": "Yes"
                },
                "c4.2xlarge": {
                    "vCPU": 8,
                    "Memory (GiB)": "15",
                    "Storage (GB)": "EBS Only",
                    "Networking Performance": "High",
                    "Physical Processor": "Intel Xeon E5-2666 v3",
                    "Clock Speed (GHz)": "2.9",
                    "Intel AVX†": "Yes",
                    "Intel AVX2†": "Yes",
                    "Intel Turbo": "Yes",
                    "EBS OPT": "Yes",
                    "Enhanced Networking†": "Yes"
                },
                "c4.4xlarge": {
                    "vCPU": 16,
                    "Memory (GiB)": "30",
                    "Storage (GB)": "EBS Only",
                    "Networking Performance": "High",
                    "Physical Processor": "Intel Xeon E5-2666 v3",
                    "Clock Speed (GHz)": "2.9",
                    "Intel AVX†": "Yes",
                    "Intel AVX2†": "Yes",
                    "Intel Turbo": "Yes",
                    "EBS OPT": "Yes",
                    "Enhanced Networking†": "Yes"
                },
                "c4.8xlarge": {
                    "vCPU": 36,
                    "Memory (GiB)": "60",
                    "Storage (GB)": "EBS Only",
                    "Networking Performance": "10 Gigabit",
                    "Physical Processor": "Intel Xeon E5-2666 v3",
                    "Clock Speed (GHz)": "2.9",
                    "Intel AVX†": "Yes",
                    "Intel AVX2†": "Yes",
                    "Intel Turbo": "Yes",
                    "EBS OPT": "Yes",
                    "Enhanced Networking†": "Yes"
                },
                "c4.large": {
                    "vCPU": 2,
                    "Memory (GiB)": "3.75",
                    "Storage (GB)": "EBS Only",
                    "Networking Performance": "Moderate",
                    "Physical Processor": "Intel Xeon E5-2666 v3",
                    "Clock Speed (GHz)": "2.9",
                    "Intel AVX†": "Yes",
                    "Intel AVX2†": "Yes",
                    "Intel Turbo": "Yes",
                    "EBS OPT": "Yes",
                    "Enhanced Networking†": "Yes"
                },
                "c4.xlarge": {
                    "vCPU": 4,
                    "Memory (GiB)": "7.5",
                    "Storage (GB)": "EBS Only",
                    "Networking Performance": "High",
                    "Physical Processor": "Intel Xeon E5-2666 v3",
                    "Clock Speed (GHz)": "2.9",
                    "Intel AVX†": "Yes",
                    "Intel AVX2†": "Yes",
                    "Intel Turbo": "Yes",
                    "EBS OPT": "Yes",
                    "Enhanced Networking†": "Yes"
                },
                "d2.2xlarge": {
                    "vCPU": 8,
                    "Memory (GiB)": "61",
                    "Storage (GB)": "6 x 2000",
                    "Networking Performance": "High",
                    "Physical Processor": "Intel Xeon E5-2676 v3",
                    "Clock Speed (GHz)": "2.4",
                    "Intel AVX†": "Yes",
                    "Intel AVX2†": "Yes",
                    "Intel Turbo": "Yes",
                    "EBS OPT": "Yes",
                    "Enhanced Networking†": "Yes"
                },
                "d2.4xlarge": {
                    "vCPU": 16,
                    "Memory (GiB)": "122",
                    "Storage (GB)": "12 x 2000",
                    "Networking Performance": "High",
                    "Physical Processor": "Intel Xeon E5-2676 v3",
                    "Clock Speed (GHz)": "2.4",
                    "Intel AVX†": "Yes",
                    "Intel AVX2†": "Yes",
                    "Intel Turbo": "Yes",
                    "EBS OPT": "Yes",
                    "Enhanced Networking†": "Yes"
                },
                "d2.8xlarge": {
                    "vCPU": 36,
                    "Memory (GiB)": "244",
                    "Storage (GB)": "24 x 2000",
                    "Networking Performance": "10 Gigabit",
                    "Physical Processor": "Intel Xeon E5-2676 v3",
                    "Clock Speed (GHz)": "2.4",
                    "Intel AVX†": "Yes",
                    "Intel AVX2†": "Yes",
                    "Intel Turbo": "Yes",
                    "EBS OPT": "Yes",
                    "Enhanced Networking†": "Yes"
                },
                "d2.xlarge": {
                    "vCPU": 4,
                    "Memory (GiB)": "30.5",
                    "Storage (GB)": "3 x 2000",
                    "Networking Performance": "Moderate",
                    "Physical Processor": "Intel Xeon E5-2676 v3",
                    "Clock Speed (GHz)": "2.4",
                    "Intel AVX†": "Yes",
                    "Intel AVX2†": "Yes",
                    "Intel Turbo": "Yes",
                    "EBS OPT": "Yes",
                    "Enhanced Networking†": "Yes"
                },
                "f1.16xlarge": {
                    "vCPU": 64,
                    "Memory (GiB)": "976",
                    "Storage (GB)": "4 x 960",
                    "Networking Performance": "High",
                    "Physical Processor": "Intel Xeon E5-2686 v4",
                    "Clock Speed (GHz)": "2.3",
                    "Intel AVX†": "Yes",
                    "Intel AVX2†": "Yes",
                    "Intel Turbo": "Yes",
                    "EBS OPT": "Yes",
                    "Enhanced Networking†": "Yes"
                },
                "f1.2xlarge": {
                    "vCPU": 8,
                    "Memory (GiB)": "122",
                    "Storage (GB)": "480 SSD",
                    "Networking Performance": "High",
                    "Physical Processor": "Intel Xeon E5-2686 v4",
                    "Clock Speed (GHz)": "2.3",
                    "Intel AVX†": "Yes",
                    "Intel AVX2†": "Yes",
                    "Intel Turbo": "Yes",
                    "EBS OPT": "Yes",
                    "Enhanced Networking†": "Yes"
                },
                "g2.2xlarge": {
                    "vCPU": 8,
                    "Memory (GiB)": "15",
                    "Storage (GB)": "1 x 60 SSD",
                    "Networking Performance": "High",
                    "Physical Processor": "Intel Xeon  E5-2670",
                    "Clock Speed (GHz)": "2.6",
                    "Intel AVX†": "Yes",
                    "Intel AVX2†": "-",
                    "Intel Turbo": "Yes",
                    "EBS OPT": "Yes",
                    "Enhanced Networking†": "-"
                },
                "g2.8xlarge": {
                    "vCPU": 32,
                    "Memory (GiB)": "60",
                    "Storage (GB)": "2 x 120 SSD",
                    "Networking Performance": "High",
                    "Physical Processor": "Intel Xeon E5-2670",
                    "Clock Speed (GHz)": "2.6",
                    "Intel AVX†": "Yes",
                    "Intel AVX2†": "-",
                    "Intel Turbo": "Yes ",
                    "EBS OPT": " -",
                    "Enhanced Networking†": "- "
                },
                "i3.16large": {
                    "vCPU": 64,
                    "Memory (GiB)": "488",
                    "Storage (GB)": "8 x 1,900 NVMe SSD",
                    "Networking Performance": "20 Gigabit",
                    "Physical Processor": "Intel Xeon E5-2686 v4",
                    "Clock Speed (GHz)": "2.3",
                    "Intel AVX†": "Yes",
                    "Intel AVX2†": "Yes",
                    "Intel Turbo": "Yes",
                    "EBS OPT": "Yes",
                    "Enhanced Networking†": "Yes"
                },
                "i3.2xlarge": {
                    "vCPU": 8,
                    "Memory (GiB)": "61",
                    "Storage (GB)": "1 x 1,900 NVMe SSD",
                    "Networking Performance": "Up to 10 Gigabit",
                    "Physical Processor": "Intel Xeon E5-2686 v4",
                    "Clock Speed (GHz)": "2.3",
                    "Intel AVX†": "Yes",
                    "Intel AVX2†": "Yes",
                    "Intel Turbo": "Yes",
                    "EBS OPT": "Yes",
                    "Enhanced Networking†": "Yes"
                },
                "i3.4xlarge": {
                    "vCPU": 16,
                    "Memory (GiB)": "122",
                    "Storage (GB)": "2 x 1,900 NVMe SSD",
                    "Networking Performance": "Up to 10 Gigabit",
                    "Physical Processor": "Intel Xeon E5-2686 v4",
                    "Clock Speed (GHz)": "2.3",
                    "Intel AVX†": "Yes",
                    "Intel AVX2†": "Yes",
                    "Intel Turbo": "Yes",
                    "EBS OPT": "Yes",
                    "Enhanced Networking†": "Yes"
                },
                "i3.8xlarge": {
                    "vCPU": 32,
                    "Memory (GiB)": "244",
                    "Storage (GB)": "4 x 1,900 NVMe SSD",
                    "Networking Performance": "10 Gigabit",
                    "Physical Processor": "Intel Xeon E5-2686 v4",
                    "Clock Speed (GHz)": "2.3",
                    "Intel AVX†": "Yes",
                    "Intel AVX2†": "Yes",
                    "Intel Turbo": "Yes",
                    "EBS OPT": "Yes",
                    "Enhanced Networking†": "Yes"
                },
                "i3.large": {
                    "vCPU": 2,
                    "Memory (GiB)": "15.25",
                    "Storage (GB)": "1 x 475 NVMe SSD",
                    "Networking Performance": "Up to 10 Gigabit",
                    "Physical Processor": "Intel Xeon E5-2686 v4",
                    "Clock Speed (GHz)": "2.3",
                    "Intel AVX†": "Yes",
                    "Intel AVX2†": "Yes",
                    "Intel Turbo": "Yes",
                    "EBS OPT": "Yes",
                    "Enhanced Networking†": "Yes"
                },
                "i3.xlarge": {
                    "vCPU": 4,
                    "Memory (GiB)": "30.5",
                    "Storage (GB)": "1 x 950 NVMe SSD",
                    "Networking Performance": "Up to 10 Gigabit",
                    "Physical Processor": "Intel Xeon E5-2686 v4",
                    "Clock Speed (GHz)": "2.3",
                    "Intel AVX†": "Yes",
                    "Intel AVX2†": "Yes",
                    "Intel Turbo": "Yes",
                    "EBS OPT": "Yes",
                    "Enhanced Networking†": "Yes"
                },
                "m3.2xlarge": {
                    "vCPU": 8,
                    "Memory (GiB)": "30",
                    "Storage (GB)": "2 x 80 SSD",
                    "Networking Performance": "High",
                    "Physical Processor": "Intel Xeon E5-2670 v2*",
                    "Clock Speed (GHz)": "2.5",
                    "Intel AVX†": "Yes",
                    "Intel AVX2†": "-",
                    "Intel Turbo": "Yes",
                    "EBS OPT": "Yes",
                    "Enhanced Networking†": "-"
                },
                "m3.large": {
                    "vCPU": 2,
                    "Memory (GiB)": "7.5",
                    "Storage (GB)": "1 x 32 SSD",
                    "Networking Performance": "Moderate",
                    "Physical Processor": "Intel Xeon E5-2670 v2*",
                    "Clock Speed (GHz)": "2.5",
                    "Intel AVX†": "Yes",
                    "Intel AVX2†": "-",
                    "Intel Turbo": "Yes",
                    "EBS OPT": "-",
                    "Enhanced Networking†": "-"
                },
                "m3.medium": {
                    "vCPU": 1,
                    "Memory (GiB)": "3.75",
                    "Storage (GB)": "1 x 4 SSD",
                    "Networking Performance": "Moderate",
                    "Physical Processor": "Intel Xeon E5-2670 v2*",
                    "Clock Speed (GHz)": "2.5",
                    "Intel AVX†": "Yes",
                    "Intel AVX2†": "-",
                    "Intel Turbo": "Yes",
                    "EBS OPT": "-",
                    "Enhanced Networking†": "-"
                },
                "m3.xlarge": {
                    "vCPU": 4,
                    "Memory (GiB)": "15",
                    "Storage (GB)": "2 x 40 SSD",
                    "Networking Performance": "High",
                    "Physical Processor": "Intel Xeon E5-2670 v2*",
                    "Clock Speed (GHz)": "2.5",
                    "Intel AVX†": "Yes",
                    "Intel AVX2†": "-",
                    "Intel Turbo": "Yes",
                    "EBS OPT": "Yes",
                    "Enhanced Networking†": "-"
                },
                "m4.10xlarge": {
                    "vCPU": 40,
                    "Memory (GiB)": "160",
                    "Storage (GB)": "EBS Only",
                    "Networking Performance": "10 Gigabit",
                    "Physical Processor": "Intel Xeon E5-2676 v3",
                    "Clock Speed (GHz)": "2.4",
                    "Intel AVX†": "Yes",
                    "Intel AVX2†": "Yes",
                    "Intel Turbo": "Yes",
                    "EBS OPT": "Yes",
                    "Enhanced Networking†": "Yes"
                },
                "m4.16xlarge": {
                    "vCPU": 64,
                    "Memory (GiB)": "256",
                    "Storage (GB)": "EBS Only",
                    "Networking Performance": "20 Gigabit",
                    "Physical Processor": "Intel Xeon E5-2686 v4",
                    "Clock Speed (GHz)": "2.3",
                    "Intel AVX†": "Yes",
                    "Intel AVX2†": "Yes",
                    "Intel Turbo": "Yes",
                    "EBS OPT": "Yes",
                    "Enhanced Networking†": "Yes"
                },
                "m4.2xlarge": {
                    "vCPU": 8,
                    "Memory (GiB)": "32",
                    "Storage (GB)": "EBS Only",
                    "Networking Performance": "High",
                    "Physical Processor": "Intel Xeon E5-2676 v3**",
                    "Clock Speed (GHz)": "2.4",
                    "Intel AVX†": "Yes",
                    "Intel AVX2†": "Yes",
                    "Intel Turbo": "Yes",
                    "EBS OPT": "Yes",
                    "Enhanced Networking†": "Yes"
                },
                "m4.4xlarge": {
                    "vCPU": 16,
                    "Memory (GiB)": "64",
                    "Storage (GB)": "EBS Only",
                    "Networking Performance": "High",
                    "Physical Processor": "Intel Xeon E5-2676 v3**",
                    "Clock Speed (GHz)": "2.4",
                    "Intel AVX†": "Yes",
                    "Intel AVX2†": "Yes",
                    "Intel Turbo": "Yes",
                    "EBS OPT": "Yes",
                    "Enhanced Networking†": "Yes"
                },
                "m4.large": {
                    "vCPU": 2,
                    "Memory (GiB)": "8",
                    "Storage (GB)": "EBS Only",
                    "Networking Performance": "Moderate",
                    "Physical Processor": "Intel Xeon E5-2676 v3**",
                    "Clock Speed (GHz)": "2.4",
                    "Intel AVX†": "Yes",
                    "Intel AVX2†": "Yes",
                    "Intel Turbo": "Yes",
                    "EBS OPT": "Yes",
                    "Enhanced Networking†": "Yes"
                },
                "m4.xlarge": {
                    "vCPU": 4,
                    "Memory (GiB)": "16",
                    "Storage (GB)": "EBS Only",
                    "Networking Performance": "High",
                    "Physical Processor": "Intel Xeon E5-2676 v3**",
                    "Clock Speed (GHz)": "2.4",
                    "Intel AVX†": "Yes",
                    "Intel AVX2†": "Yes",
                    "Intel Turbo": "Yes",
                    "EBS OPT": "Yes",
                    "Enhanced Networking†": "Yes"
                },
                "p2.16xlarge": {
                    "vCPU": 64,
                    "Memory (GiB)": "732",
                    "Storage (GB)": "EBS Only",
                    "Networking Performance": "20 Gigabit",
                    "Physical Processor": "Intel Xeon E5-2686 v4",
                    "Clock Speed (GHz)": "2.3",
                    "Intel AVX†": "Yes",
                    "Intel AVX2†": "Yes",
                    "Intel Turbo": "Yes",
                    "EBS OPT": "Yes",
                    "Enhanced Networking†": "Yes"
                },
                "p2.8xlarge": {
                    "vCPU": 32,
                    "Memory (GiB)": "488",
                    "Storage (GB)": "EBS Only",
                    "Networking Performance": "10 Gigabit",
                    "Physical Processor": "Intel Xeon E5-2686 v4",
                    "Clock Speed (GHz)": "2.3",
                    "Intel AVX†": "Yes",
                    "Intel AVX2†": "Yes",
                    "Intel Turbo": "Yes",
                    "EBS OPT": "Yes",
                    "Enhanced Networking†": "Yes"
                },
                "p2.xlarge": {
                    "vCPU": 4,
                    "Memory (GiB)": "61",
                    "Storage (GB)": "EBS Only",
                    "Networking Performance": "High",
                    "Physical Processor": "Intel Xeon E5-2686 v4",
                    "Clock Speed (GHz)": "2.3",
                    "Intel AVX†": "Yes",
                    "Intel AVX2†": "Yes",
                    "Intel Turbo": "Yes",
                    "EBS OPT": "Yes",
                    "Enhanced Networking†": "Yes"
                },
                "r3.2xlarge": {
                    "vCPU": 8,
                    "Memory (GiB)": "61",
                    "Storage (GB)": "1 x 160 SSD",
                    "Networking Performance": "High",
                    "Physical Processor": "Intel Xeon E5-2670 v2",
                    "Clock Speed (GHz)": "2.5",
                    "Intel AVX†": "Yes",
                    "Intel AVX2†": "-",
                    "Intel Turbo": "Yes",
                    "EBS OPT": "Yes",
                    "Enhanced Networking†": "Yes"
                },
                "r3.4xlarge": {
                    "vCPU": 16,
                    "Memory (GiB)": "122",
                    "Storage (GB)": "1 x 320 SSD",
                    "Networking Performance": "High",
                    "Physical Processor": "Intel Xeon E5-2670 v2",
                    "Clock Speed (GHz)": "2.5",
                    "Intel AVX†": "Yes",
                    "Intel AVX2†": "-",
                    "Intel Turbo": "Yes",
                    "EBS OPT": "Yes",
                    "Enhanced Networking†": "Yes"
                },
                "r3.8xlarge": {
                    "vCPU": 32,
                    "Memory (GiB)": "244",
                    "Storage (GB)": "2 x 320 SSD",
                    "Networking Performance": "10 Gigabit",
                    "Physical Processor": "Intel Xeon E5-2670 v2",
                    "Clock Speed (GHz)": "2.5",
                    "Intel AVX†": "Yes",
                    "Intel AVX2†": "-",
                    "Intel Turbo": "Yes",
                    "EBS OPT": "-",
                    "Enhanced Networking†": "Yes"
                },
                "r3.large": {
                    "vCPU": 2,
                    "Memory (GiB)": "15.25",
                    "Storage (GB)": "1 x 32 SSD",
                    "Networking Performance": "Moderate",
                    "Physical Processor": "Intel Xeon E5-2670 v2",
                    "Clock Speed (GHz)": "2.5",
                    "Intel AVX†": "Yes",
                    "Intel AVX2†": "-",
                    "Intel Turbo": "Yes",
                    "EBS OPT": "-",
                    "Enhanced Networking†": "Yes"
                },
                "r3.xlarge": {
                    "vCPU": 4,
                    "Memory (GiB)": "30.5",
                    "Storage (GB)": "1 x 80 SSD",
                    "Networking Performance": "Moderate",
                    "Physical Processor": "Intel Xeon E5-2670 v2",
                    "Clock Speed (GHz)": "2.5",
                    "Intel AVX†": "Yes",
                    "Intel AVX2†": "-",
                    "Intel Turbo": "Yes",
                    "EBS OPT": "Yes",
                    "Enhanced Networking†": "Yes"
                },
                "r4.16xlarge": {
                    "vCPU": 64,
                    "Memory (GiB)": "488",
                    "Storage (GB)": "-",
                    "Networking Performance": "20 Gigabit",
                    "Physical Processor": "Intel Xeon E5-2686 v4",
                    "Clock Speed (GHz)": "2.3",
                    "Intel AVX†": "Yes",
                    "Intel AVX2†": "Yes",
                    "Intel Turbo": "Yes",
                    "EBS OPT": "Yes",
                    "Enhanced Networking†": "Yes"
                },
                "r4.2xlarge": {
                    "vCPU": 8,
                    "Memory (GiB)": "61",
                    "Storage (GB)": "-",
                    "Networking Performance": "Up to 10 Gigabit",
                    "Physical Processor": "Intel Xeon E5-2686 v4",
                    "Clock Speed (GHz)": "2.3",
                    "Intel AVX†": "Yes",
                    "Intel AVX2†": "Yes",
                    "Intel Turbo": "Yes",
                    "EBS OPT": "Yes",
                    "Enhanced Networking†": "Yes"
                },
                "r4.4xlarge": {
                    "vCPU": 16,
                    "Memory (GiB)": "122",
                    "Storage (GB)": "-",
                    "Networking Performance": "Up to 10 Gigabit",
                    "Physical Processor": "Intel Xeon E5-2686 v4",
                    "Clock Speed (GHz)": "2.3",
                    "Intel AVX†": "Yes",
                    "Intel AVX2†": "Yes",
                    "Intel Turbo": "Yes",
                    "EBS OPT": "Yes",
                    "Enhanced Networking†": "Yes"
                },
                "r4.8xlarge": {
                    "vCPU": 32,
                    "Memory (GiB)": "244",
                    "Storage (GB)": "-",
                    "Networking Performance": "10 Gigabit",
                    "Physical Processor": "Intel Xeon E5-2686 v4",
                    "Clock Speed (GHz)": "2.3",
                    "Intel AVX†": "Yes",
                    "Intel AVX2†": "Yes",
                    "Intel Turbo": "Yes",
                    "EBS OPT": "Yes",
                    "Enhanced Networking†": "Yes"
                },
                "r4.large": {
                    "vCPU": 2,
                    "Memory (GiB)": "15.25",
                    "Storage (GB)": "-",
                    "Networking Performance": "Up to 10 Gigabit",
                    "Physical Processor": "Intel Xeon E5-2686 v4",
                    "Clock Speed (GHz)": "2.3",
                    "Intel AVX†": "Yes",
                    "Intel AVX2†": "Yes",
                    "Intel Turbo": "Yes",
                    "EBS OPT": "Yes",
                    "Enhanced Networking†": "Yes"
                },
                "r4.xlarge": {
                    "vCPU": 4,
                    "Memory (GiB)": "30.5",
                    "Storage (GB)": "-",
                    "Networking Performance": "Up to 10 Gigabit",
                    "Physical Processor": "Intel Xeon E5-2686 v4",
                    "Clock Speed (GHz)": "2.3",
                    "Intel AVX†": "Yes",
                    "Intel AVX2†": "Yes",
                    "Intel Turbo": "Yes",
                    "EBS OPT": "Yes",
                    "Enhanced Networking†": "Yes"
                },
                "t2.2xlarge": {
                    "vCPU": 8,
                    "Memory (GiB)": "32",
                    "Storage (GB)": "EBS Only",
                    "Networking Performance": "Moderate",
                    "Physical Processor": "Intel Xeon family",
                    "Clock Speed (GHz)": "Up to 3.0",
                    "Intel AVX†": "Yes",
                    "Intel AVX2†": "-",
                    "Intel Turbo": "Yes",
                    "EBS OPT": "-",
                    "Enhanced Networking†": "-"
                },
                "t2.large": {
                    "vCPU": 2,
                    "Memory (GiB)": "8",
                    "Storage (GB)": "EBS Only",
                    "Networking Performance": "Low to Moderate",
                    "Physical Processor": "Intel Xeon family",
                    "Clock Speed (GHz)": "Up to 3.0",
                    "Intel AVX†": "Yes",
                    "Intel AVX2†": "-",
                    "Intel Turbo": "Yes",
                    "EBS OPT": "-",
                    "Enhanced Networking†": "-"
                },
                "t2.medium": {
                    "vCPU": 2,
                    "Memory (GiB)": "4",
                    "Storage (GB)": "EBS Only",
                    "Networking Performance": "Low to Moderate",
                    "Physical Processor": "Intel Xeon family",
                    "Clock Speed (GHz)": "Up to 3.3",
                    "Intel AVX†": "Yes",
                    "Intel AVX2†": "-",
                    "Intel Turbo": "Yes",
                    "EBS OPT": "-",
                    "Enhanced Networking†": "-"
                },
                "t2.micro": {
                    "vCPU": 1,
                    "Memory (GiB)": "1",
                    "Storage (GB)": "EBS Only",
                    "Networking Performance": "Low to Moderate",
                    "Physical Processor": "Intel Xeon family",
                    "Clock Speed (GHz)": "Up to 3.3",
                    "Intel AVX†": "Yes",
                    "Intel AVX2†": "-",
                    "Intel Turbo": "Yes",
                    "EBS OPT": "-",
                    "Enhanced Networking†": "-"
                },
                "t2.nano": {
                    "vCPU": 1,
                    "Memory (GiB)": "0.5",
                    "Storage (GB)": "EBS Only",
                    "Networking Performance": "Low",
                    "Physical Processor": "Intel Xeon family",
                    "Clock Speed (GHz)": "up to 3.3",
                    "Intel AVX†": "Yes",
                    "Intel AVX2†": "-",
                    "Intel Turbo": "Yes",
                    "EBS OPT": "-",
                    "Enhanced Networking†": "-"
                },
                "t2.small": {
                    "vCPU": 1,
                    "Memory (GiB)": "2",
                    "Storage (GB)": "EBS Only",
                    "Networking Performance": "Low to Moderate",
                    "Physical Processor": "Intel Xeon family",
                    "Clock Speed (GHz)": "Up to 3.3",
                    "Intel AVX†": "Yes",
                    "Intel AVX2†": "-",
                    "Intel Turbo": "Yes",
                    "EBS OPT": "-",
                    "Enhanced Networking†": "-"
                },
                "t2.xlarge": {
                    "vCPU": 4,
                    "Memory (GiB)": "16",
                    "Storage (GB)": "EBS Only",
                    "Networking Performance": "Moderate",
                    "Physical Processor": "Intel Xeon family",
                    "Clock Speed (GHz)": "Up to 3.0",
                    "Intel AVX†": "Yes",
                    "Intel AVX2†": "-",
                    "Intel Turbo": "Yes",
                    "EBS OPT": "-",
                    "Enhanced Networking†": "-"
                },
                "x1.16large": {
                    "vCPU": 64,
                    "Memory (GiB)": "976",
                    "Storage (GB)": "1 x 1,920 SSD",
                    "Networking Performance": "10 Gigabit",
                    "Physical Processor": "Intel Xeon E7-8880 v3",
                    "Clock Speed (GHz)": "2.3",
                    "Intel AVX†": "Yes",
                    "Intel AVX2†": "Yes",
                    "Intel Turbo": "Yes",
                    "EBS OPT": "Yes",
                    "Enhanced Networking†": "Yes"
                },
                "x1.32xlarge": {
                    "vCPU": 128,
                    "Memory (GiB)": "1,952",
                    "Storage (GB)": "2 x 1,920 SSD",
                    "Networking Performance": "20 Gigabit",
                    "Physical Processor": "Intel Xeon E7-8880 v3",
                    "Clock Speed (GHz)": "2.3",
                    "Intel AVX†": "Yes",
                    "Intel AVX2t": "Yes",
                    "Intel Turbo": "Yes",
                    "EBS OPT": "Yes",
                    "Enhanced Networking†": "Yes"
                }
            }
        return instanceMap[instance]

    def getInstanceVCPU(self):
        return self.instanceType['vCPU']
    def getInstanceMemory(self):
        return self.instanceType['Memory (GiB)']
    def getInstanceStorage(self):
        return self.instanceType['Storage (GB)']
    def getInstanceNetworkPerformance(self):
        return self.instanceType['Networking Performance']
    def getInstancePhysicalProcessor(self):
        return self.instanceType['Physical Processor']
    def getInstanceClockSpeed(self):
        return self.instanceType['Clock Speed (GHz)']
    def getInstanceIntelAVX(self):
        return self.instanceType['Intel AVX†']
    def getInstanceIntelAVX2(self):
        return self.instanceType['Intel AVX2t']
    def getInstanceIntelTurbo(self):
        return self.instanceType['Intel Turbo']
    def getInstanceEBSOPT(self):
        return self.instanceType['EBS OPT']
    def getInstanceEnhancedNetworking(self):
        return self.instanceType['Enhanced Networking†']

if __name__=='__main__':
    x1x3large = AWSInstanceType('x1.32xlarge')
    print(x1x3large.getInstanceVCPU())
    print(x1x3large.getInstanceMemory())
